name: a sample workflow

on:
 push:
   branches:
     - main
 workflow_dispatch:

env:
  COMMIT_ID: 498125cbeb774ef56e969b5cec186323e5f846ea
  IMAGE_NAME: samplerepo

jobs:
  push_build_deploy:
     runs-on: ubuntu-latest

     steps:
       - name: checkout samplewebsite Repository
         uses: actions/checkout@v4

       - name: Login to Docker Hub
               uses: docker/login-action@v4
               with: 
                 username=${{ secrets.DOCKERHUB_USERNAME }}
                 password=${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build image
         run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }} .

       - name: Tag latest
         run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

       - name: Push commit image
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}

       - name: Push latest image
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
  
